In [46]:
#matrix multiplication
import numpy as num
a=num.array([[1,2,3],[4,5,6],[7,8,9]])
b=num.array([[2,5,6],[8,9,1],[4,7,3]])
print("matrix a:\n",a)
print("matrix b:\n",b)
c=num.dot(a,b)
print("matrix multiplication:\n",c)
d=num.transpose(c)
print("transpose:\n",d)

matrix a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix b:
 [[2 5 6]
 [8 9 1]
 [4 7 3]]
matrix multiplication:
 [[ 30  44  17]
 [ 72 107  47]
 [114 170  77]]
transpose:
 [[ 30  72 114]
 [ 44 107 170]
 [ 17  47  77]]


In [49]:
a=num.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(b)
k=b.ravel()
print(k)
print("matrix slicing:",b[0:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
matrix slicing: [[2 3]
 [5 6]
 [8 9]]


In [11]:
a=num.arange(9)
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
a=num.zeros([3,3],dtype='i')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
